/**
 * Copies the contract ABIs (from Foundry's build output) and the testnet deployment addresses into
 * src/lib/generated.ts, typed `as const` so wagmi/viem infer argument and return types.
 *
 *   forge build (in contracts/) && pnpm -C app sync-abis
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const contracts = ["RRUSD", "RackOracle", "SeriesFactory", "Series", "OutcomeToken", "HedgeRouter", "MarketRegistry"];

let out = "// Generated by scripts/sync-abis.mts from contracts/out and contracts/deployments. Do not edit.\n\n";
const dep = JSON.parse(readFileSync(resolve(root, "contracts", "deployments", "10143.json"), "utf8"));
out += `export const deployment = ${JSON.stringify(dep, null, 2)} as const;\n\n`;
for (const c of contracts) {
  const abi = JSON.parse(readFileSync(resolve(root, "contracts", "out", `${c}.sol`, `${c}.json`), "utf8")).abi;
  const name = c.charAt(0).toLowerCase() + c.slice(1);
  out += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n\n`;
}
writeFileSync(resolve(import.meta.dirname, "..", "src", "lib", "generated.ts"), out);
console.log(`wrote ${contracts.length} ABIs and the 10143 deployment to src/lib/generated.ts`);
