/**
 * Copies the real-price reference (bots/src/lib/reference.ts) into src/lib/reference.ts, so the app computes the
 * H100 index exactly as the publishers do while building from the app folder alone (as on Railway).
 *
 *   pnpm -C app sync-reference
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const src = readFileSync(resolve(root, "bots", "src", "lib", "reference.ts"), "utf8");
const out = `// Generated by scripts/sync-reference.mts from bots/src/lib/reference.ts. Do not edit.\n\n${src}`;
writeFileSync(resolve(import.meta.dirname, "..", "src", "lib", "reference.ts"), out);
console.log("wrote src/lib/reference.ts");
